function [fitresult, gof] = FitGauss1(X,ptLine,bstart)
%CREATEFIT(PTLINE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: ptLine
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Mar-2019 09:47:28


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( X, ptLine );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.StartPoint = [129.697280088725 bstart 12.0278863495252];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'ptLine', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% ylabel ptLine
% grid on


